'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.
'''


def fibonacci(number):
    toplam=0
    nums=[]
    nums.append(0)
    nums.append(1)
    for i in range(2,number):
        sayi=nums[i-1]+nums[i-2]
        nums.append(sayi)
        if nums[i]%2==0:
            if nums[i]>number:
                break
            toplam=toplam+nums[i]

    print(nums)
    print(toplam)

fibonacci(100000)



